#设置程序端口号
server:
  port: 8087
  tomcat:
    #最大连接数
    max-connections: 10000
    threads:
      #最大线程数
      max: 200

#设置激活的启动环境，这里为dev
spring:
  profiles:
    active: dev

  #email
  mail:
    host: smtp.qq.com
    username: 1919176648@qq.com
    password: yygqwtnuvpbgcigc
    port: 465
    protocol: smtps
    from: 1919176648@qq.com
    #设置为SSL协议
    properties:
      mail:
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory



#查看执行的 sql 语句
mybatis-plus:
  configuration:

    #解决带_ 的时候获取不到值,自动驼峰转换关闭
    map-underscore-to-camel-case: false

#配置pagehelper方言为mysql
pagehelper:
  helper-dialect: mysql


