package com.bookticket.pojo;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;

/**
 * @TableName trips
 */
@Data
@TableName(value = "trips")
public class Trips implements Serializable {
    /**
     * 编号
     *
     */
    @TableId(type = IdType.AUTO)
    private Integer trips_id;

    /**
     * 线路编号
     *
     */
    private Integer trips_line_id;

    /**
     * 航班名称
     *
     */
    private String trips_flight_name;

    /**
     * 出发时间
     *
     */
    private Date trips_start_time;

    /**
     * 到达时间
     *
     */
    private Date trips_end_time;

    /**
     * 商务舱剩余座位数量
     *
     */
    private Integer business_class_seat_num;

    /**
     * 经济舱剩余座位数量
     *
     */
    private Integer economy_class_seat_num;

    /**
     * 商务舱票价
     *
     */
    private Float business_class_seat_price;

    /**
     * 经济舱票价
     *
     */
    private Float economy_class_seat_price;

    /**
     * 逻辑删除（0 未删除、1 删除）
     *
     */
    @TableLogic(value = "0", delval = "1")
    @TableField(fill = FieldFill.INSERT)
    private Integer trips_delete_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trips
     *
     */
    //增加两个冗余属性（不在数据库中存在）
    @TableField(exist = false)
    private String trips_start_station_name;//起始站点名
    @TableField(exist = false)
    private String trips_end_station_name;//到达站点名



    public String getTrips_start_station_name() {
        return trips_start_station_name;
    }

    public void setTrips_start_station_name(String trips_start_station_name) {
        this.trips_start_station_name = trips_start_station_name;
    }

    public String getTrips_end_station_name() {
        return trips_end_station_name;
    }

    public void setTrips_end_station_name(String trips_end_station_name) {
        this.trips_end_station_name = trips_end_station_name;
    }

//    public Integer getId() {
//        return this.trips_id;
//    }
}
